const sampleFrames = [
  {
    id: 1,
    name: 'Elegant White Frame',
    language: 'English',
    frameSize: 'Medium',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139905/IMG-20241109-WA0026_g0zm9u.jpg",
    description: 'A beautifully crafted White frame.',
    orientation: 'vertical',
    price: 1500,
  },
  {
    id: 2,
    name: 'Classic Wooden Frame',
    language: ' Arabic',
    frameSize: 'Large',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139904/IMG-20241109-WA0017_ptyohv.jpg",
    description: 'A timeless classic wooden frame.',
    orientation: 'horizontal',
    price: 2000,
  },
  {
    id: 3,
    name: 'Modern Art Frame',
    language: 'Arabic',
    frameSize: 'Small',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139905/IMG-20241109-WA0025_rw5stb.jpg",
    description: 'A stylish modern art frame.',
    orientation: 'vertical',
    price: 1000,
  },
  {
    id: 4,
    name: 'Rustic Barnwood Frame',
    language: 'Arabic',
    frameSize: 'Medium',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139905/IMG-20241109-WA0018_uphwrk.jpg",
    description: 'A rustic barnwood frame perfect for any photo.',
    orientation: 'horizontal',
    price: 1500,
  },
  {
    id: 5,
    name: 'Vintage  Frame',
    language: 'Arabic',
    frameSize: 'Large',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139904/IMG-20241109-WA0021_vevdpp.jpg",
    description: 'A vintage frame with arabic designs.',
    orientation: 'vertical',
    price: 2000,
  },
  {
    id: 6,
    name: 'Sleek Wooden Frame',
    language: 'Arabic & English',
    frameSize: 'Small',
    image: "https://res.cloudinary.com/ddi2gnim6/image/upload/v1731139904/IMG-20241109-WA0015_svfnlj.jpg",
    description: 'A sleek wooden frame with a quote written.',
    orientation: 'horizontal',
    price: 1000,
  },
];

export default sampleFrames;
